### ISSUE TITLE
Unable to download program guide

### ISSUE THREAD

**Issue by rdefino** [Slugger/sdjson-api#5]
I'm seeing the following in the log after upgrading to .081beta SD epg plugin

Caused by: org.schedulesdirect.api.exception.InvalidJsonObjectException: Program[SP003182260000]: JSONArray[1] is not a JSONObject.
    at org.schedulesdirect.api.Program.<init>(Program.java:749)
    at org.schedulesdirect.api.ZipEpgClient.fetchProgram(ZipEpgClient.java:301)
    at org.schedulesdirect.api.ZipEpgClient.fetchSchedule(ZipEpgClient.java:270)
    at org.schedulesdirect.api.ZipEpgClient.fetchSchedules(ZipEpgClient.java:319)
    at org.schedulesdirect.api.Lineup.fetchDetails(Lineup.java:139)
    at org.schedulesdirect.api.ZipEpgClient.getLineups(ZipEpgClient.java:360)
    at org.schedulesdirect.api.ZipEpgClient$getLineups.call(Unknown Source)
    at sagex.epg.schedulesdirect.EPGImportPluginSchedulesDirect.getProviders(EPGImportPluginSchedulesDirect.groovy:125)
    at sage.EPGImportPlugin$getProviders.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at sage.EPGImportPlugin$getProviders.call(Unknown Source)
    at sagex.epg.schedulesdirect.plugin.Plugin.forceEpgRefresh(Plugin.groovy:128)
    at sagex.epg.schedulesdirect.plugin.Plugin.forceEpgRefresh(Plugin.groovy)
    at sagex.epg.schedulesdirect.plugin.Plugin.refreshEpgData(Plugin.groovy:203)
    ... 30 more
Caused by: org.json.JSONException: JSONArray[1] is not a JSONObject.
    at org.json.JSONArray.getJSONObject(JSONArray.java:296)
    at org.schedulesdirect.api.Program.<init>(Program.java:725)
    ... 43 more
2015-04-28 13:42:14,137 WARN  [Plugin]: Failed to handle ButtonClickHandler: 'sdepg/refresh' in class: sagex.epg.schedulesdirect.plugin.Pl

**Comment by Slugger** [comment]
Root cause is bad upstream data from SD with the team data for sports events.  When the data follows the spec, there are no problems.  However, when the data is bad, the client shouldn't bomb out with exceptions.  Instead, just ignore the data and drop it (with a warning in the api logs).
